// lib/models/models.dart
/// 📦 Office Syndrome Helper - Models Export File
/// รวบรวม Models ทั้งหมดไว้ในที่เดียวเพื่อง่ายต่อการ import

// Core Models
export 'user_settings.dart';
export 'pain_point.dart';
export 'treatment.dart';
export 'notification_session.dart';

// Generated Files (จะถูกสร้างโดย build_runner)
// These will be auto-generated by Hive
// export 'user_settings.g.dart';
// export 'pain_point.g.dart';
// export 'treatment.g.dart';
// export 'notification_session.g.dart';

/// 🏷️ Model Type Definitions
/// ใช้สำหรับ Type Safety และ Intellisense

/// User Settings Related Types
typedef UserSettingsMap = Map<String, dynamic>;
typedef PainPointsList = List<PainPoint>;
typedef WorkingHours
    = Map<String, String>; // {'start': '09:00', 'end': '17:00'}
typedef WorkingDays = List<int>; // [1,2,3,4,5] for Mon-Fri

/// Treatment Related Types
typedef TreatmentsList = List<Treatment>;
typedef TreatmentsByPainPoint = Map<String, List<Treatment>>;
typedef ExerciseDuration = int; // in minutes

/// Notification Related Types
typedef NotificationSessionsList = List<NotificationSession>;
typedef SessionStatus = String; // 'pending', 'completed', 'skipped', 'missed'
typedef SessionId = String; // UUID

/// Analytics Related Types
typedef AnalyticsData = Map<String, dynamic>;
typedef StatsMap = Map<String, dynamic>;
typedef TrendData = List<Map<String, dynamic>>;

/// 🎯 Model Constants
class ModelConstants {
  // Hive Type IDs (ต้องตรงกับที่กำหนดใน Models)
  static const int userSettingsTypeId = 1;
  static const int painPointTypeId = 2;
  static const int treatmentTypeId = 3;
  static const int notificationSessionTypeId = 4;

  // Pain Point IDs
  static const Map<String, int> painPointIds = {
    'ศีรษะ': 0,
    'ตา': 1,
    'คอ': 2,
    'บ่าและไหล่': 3,
    'หลังส่วนบน': 4,
    'หลังส่วนล่าง': 5,
    'แขน/ศอก': 6,
    'ข้อมือ/มือ/นิ้ว': 7,
    'ขา': 8,
    'เท้า': 9,
  };

  // Session Status Values
  static const String sessionPending = 'pending';
  static const String sessionCompleted = 'completed';
  static const String sessionSkipped = 'skipped';
  static const String sessionMissed = 'missed';

  // Default Settings
  static const int defaultIntervalMinutes = 60;
  static const String defaultStartTime = '09:00';
  static const String defaultEndTime = '17:00';
  static const List<int> defaultWorkingDays = [1, 2, 3, 4, 5]; // Mon-Fri
  static const int maxPainPointSelection = 3;
  static const int defaultTreatmentCount = 2;

  // Limits
  static const int minIntervalMinutes = 15;
  static const int maxIntervalMinutes = 240; // 4 hours
  static const int maxSnoozeCount = 3;
  static const int maxSessionHistoryDays = 90;
}

/// 🔧 Model Utilities
class ModelUtils {
  /// แปลง PainPoint list เป็น String list
  static List<String> painPointsToStrings(List<PainPoint> painPoints) {
    return painPoints.map((p) => p.name).toList();
  }

  /// แปลง String list เป็น PainPoint list
  static List<PainPoint> stringsToPainPoints(List<String> names) {
    return names
        .map((name) => PainPoint(
              id: ModelConstants.painPointIds[name] ?? 0,
              name: name,
              isSelected: true,
            ))
        .toList();
  }

  /// แปลง Treatment list เป็น JSON
  static List<Map<String, dynamic>> treatmentsToJson(
      List<Treatment> treatments) {
    return treatments.map((t) => t.toJson()).toList();
  }

  /// แปลง JSON เป็น Treatment list
  static List<Treatment> treatmentsFromJson(List<dynamic> jsonList) {
    return jsonList.map((json) => Treatment.fromJson(json)).toList();
  }

  /// สร้าง NotificationSession ID ใหม่
  static String generateSessionId() {
    return DateTime.now().millisecondsSinceEpoch.toString() +
        DateTime.now().microsecond.toString();
  }

  /// ตรวจสอบว่า Session ใช้งานได้หรือไม่
  static bool isValidSession(NotificationSession? session) {
    if (session == null) return false;

    // ตรวจสอบข้อมูลพื้นฐาน
    if (session.id.isEmpty ||
        session.painPoint.isEmpty ||
        session.treatments.isEmpty) {
      return false;
    }

    // ตรวจสอบว่าไม่เก่าเกินไป (24 ชั่วโมง)
    final now = DateTime.now();
    final sessionAge = now.difference(session.timestamp);
    if (sessionAge.inHours > 24) {
      return false;
    }

    return true;
  }

  /// รับสีของ Pain Point
  static int getPainPointColorIndex(String painPointName) {
    return ModelConstants.painPointIds[painPointName] ?? 0;
  }

  /// ตรวจสอบว่าอยู่ในเวลาทำงานหรือไม่
  static bool isWithinWorkingHours(DateTime dateTime, UserSettings settings) {
    final timeOfDay = TimeOfDay.fromDateTime(dateTime);
    final currentMinutes = timeOfDay.hour * 60 + timeOfDay.minute;

    // แปลง working hours เป็นนาที
    final startParts = settings.workingHoursStart.split(':');
    final endParts = settings.workingHoursEnd.split(':');

    final startMinutes =
        int.parse(startParts[0]) * 60 + int.parse(startParts[1]);
    final endMinutes = int.parse(endParts[0]) * 60 + int.parse(endParts[1]);

    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
  }

  /// ตรวจสอบว่าเป็นวันทำงานหรือไม่
  static bool isWorkingDay(DateTime dateTime, UserSettings settings) {
    return settings.workingDays.contains(dateTime.weekday);
  }

  /// คำนวณเวลาแจ้งเตือนครั้งถัดไป
  static DateTime calculateNextNotification(UserSettings settings) {
    final now = DateTime.now();

    if (settings.lastNotificationTime == null) {
      // ครั้งแรก - เริ่มจากตอนนี้
      return now.add(Duration(minutes: settings.intervalMinutes));
    }

    // ครั้งถัดไป - จาก lastNotificationTime + interval
    return settings.lastNotificationTime!
        .add(Duration(minutes: settings.intervalMinutes));
  }
}

/// 🎨 Model Extensions
extension UserSettingsExtension on UserSettings {
  /// ตรวจสอบว่าการตั้งค่าครบถ้วนหรือไม่
  bool get isComplete {
    return selectedPainPoints.isNotEmpty &&
        intervalMinutes >= ModelConstants.minIntervalMinutes &&
        intervalMinutes <= ModelConstants.maxIntervalMinutes &&
        workingHoursStart.isNotEmpty &&
        workingHoursEnd.isNotEmpty &&
        workingDays.isNotEmpty;
  }

  /// รับเวลาทำงานในรูปแบบ Duration
  Duration get workingDuration {
    final startParts = workingHoursStart.split(':');
    final endParts = workingHoursEnd.split(':');

    final startMinutes =
        int.parse(startParts[0]) * 60 + int.parse(startParts[1]);
    final endMinutes = int.parse(endParts[0]) * 60 + int.parse(endParts[1]);

    return Duration(minutes: endMinutes - startMinutes);
  }

  /// คำนวณจำนวนแจ้งเตือนต่อวัน
  int get notificationsPerDay {
    final workingMinutes = workingDuration.inMinutes;
    return (workingMinutes / intervalMinutes).floor();
  }
}

extension NotificationSessionExtension on NotificationSession {
  /// ตรวจสอบว่า Session เสร็จสิ้นแล้วหรือไม่
  bool get isCompleted => status == ModelConstants.sessionCompleted;

  /// ตรวจสอบว่า Session ถูกข้ามหรือไม่
  bool get isSkipped => status == ModelConstants.sessionSkipped;

  /// ตรวจสอบว่า Session พลาดหรือไม่
  bool get isMissed => status == ModelConstants.sessionMissed;

  /// ตรวจสอบว่า Session รอดำเนินการหรือไม่
  bool get isPending => status == ModelConstants.sessionPending;

  /// รับระยะเวลาที่ผ่านมาตั้งแต่สร้าง Session
  Duration get age => DateTime.now().difference(timestamp);

  /// ตรวจสอบว่า Session หมดอายุหรือไม่ (1 ชั่วโมง)
  bool get isExpired => age.inHours >= 1;

  /// รับจำนวนท่าออกกำลังกาย
  int get treatmentCount => treatments.length;

  /// รับเวลารวมของการออกกำลังกาย
  int get totalDurationMinutes {
    return treatments.fold(
        0, (sum, treatment) => sum + (treatment.durationMinutes ?? 0));
  }
}

extension TreatmentExtension on Treatment {
  /// ตรวจสอบว่ามีรูปภาพหรือไม่
  bool get hasImage => imageUrl != null && imageUrl!.isNotEmpty;

  /// ตรวจสอบว่ามีคำอธิบายหรือไม่
  bool get hasDescription => description.isNotEmpty;

  /// รับระยะเวลาในรูปแบบ Duration
  Duration get duration => Duration(minutes: durationMinutes ?? 0);

  /// ตรวจสอบว่าเป็นท่าง่ายหรือไม่ (น้อยกว่า 3 นาที)
  bool get isEasy => (durationMinutes ?? 0) <= 3;

  /// ตรวจสอบว่าเป็นท่ายากหรือไม่ (มากกว่า 5 นาที)
  bool get isHard => (durationMinutes ?? 0) > 5;
}
